#!/bin/sh

CWD=`pwd`
GITUSER='git'
GITSERVER='git.osuosl.org'
PUPPETSUPERPROJECT='puppet/puppet.git'
SSHKEY='/var/lib/gitolite/.ssh/id_rsa.puppet'
PUPPETUSER='puppet'
PUPPETSERVER='puppet2.osuosl.org'

REPO="${GITUSER}@${GITSERVER}:${PUPPETSUPERPROJECT}"
DEPLOY="/etc/puppet/environments"
SSH_ARGS="-i ${SSHKEY}"
PUPPETMASTER="${PUPPETUSER}@${PUPPETSERVER}"
SYNC_COMMAND="/usr/local/bin/puppetsubsync"

echo "puppetsubsync"
while read oldrev newrev refname
do
  BRANCH=`echo ${refname} | sed -n 's/^refs\/heads\///p'`
  echo "Branch is ${BRANCH}"
  if echo ${BRANCH} | egrep '^t_' > /dev/null; then

    echo "Detecting leading t_ on branchname, submodule cloning..."

    [ "${newrev}" -eq 0 ] 2> /dev/null && DELETE='--delete' || DELETE=''

    echo ssh ${SSH_ARGS} "${PUPPETMASTER}" "${SYNC_COMMAND}" \
      --branch "${BRANCH}" \
      --repository "${REPO}" \
      --deploy "${DEPLOY}" \
      ${DELETE}
  fi
done
