#!/bin/sh

CWD=`pwd`
GITUSER='git'
GITSERVER='git.osuosl.org'
PUPPETSUPERPROJECT='puppet/puppet.git'
SSHKEY='/var/lib/gitolite/.ssh/id_rsa.puppet'
PUPPETUSER='puppet'
PUPPETSERVER='puppet2.osuosl.org'

REPO="${GITUSER}@${GITSERVER}:${PUPPETSUPERPROJECT}"
DEPLOY="/etc/puppet/environments"
SSH_ARGS="-i ${SSHKEY}"
PUPPETMASTER="${PUPPETUSER}@${PUPPETSERVER}"
SYNC_COMMAND="/usr/local/bin/puppetsubsync"

SUBSYNC="ssh ${SSH_ARGS} "${PUPPETMASTER}" "${SYNC_COMMAND}""

while read oldrev newrev refname
do
    BRANCH=`echo ${refname} | sed -n 's/^refs\/heads\///p'`
    if [[ "${newrev}" = "0000000000000000000000000000000000000000" ]]; then
        # Delete the environment.
        echo "Deleting environment. (${oldrev}, ${newrev}, ${refname})"
        ${SUBSYNC} --deploy "${DEPLOY}" --branch "${BRANCH}" --delete $@
    elif echo ${BRANCH} | egrep '^t_' > /dev/null; then
        # Make or update a test environment.
        echo "Detecting leading t_ on branchname, cloning a testing environment."
        ${SUBSYNC} --branch "${BRANCH}" --remote "${REPO}" --deploy "${DEPLOY}" --test $@
    else
        # Make or update a standard environment.
        echo "Cloning a standard environment."
        ${SUBSYNC} --branch "${BRANCH}" --remote "${REPO}" --deploy "${DEPLOY}" $@
    fi
done
