#!/bin/bash
# trigger remote ssh commands

sudo="$(git config hooks.sshtrigger-sudo)"
sshkey="$(git config hooks.sshtrigger-sshkey)"
sshopts="$(git config hooks.sshtrigger-sshopts)"
target="$(git config hooks.sshtrigger-target)"

if [ -n ${sudo} ] ; then
    sudo /usr/bin/ssh -i ${ssh_key} -o StrictHostKeyChecking=no \
        -o BatchMode=yes ${sshopts} ${target} >/dev/null 2>&1
else
    /usr/bin/ssh -i ${ssh_key} -o StrictHostKeyChecking=no \
        -o BatchMode=yes ${sshopts} ${target} >/dev/null 2>&1
fi
